### ISSUE TITLE
Add time key to parameters

### ISSUE THREAD

**Issue by jgladwig** [siftech/funman#16]
Check whether the Terrarium syntax for time dependent parameters would be a better representation. Otherwise, parameters are of the form:
```
{
  "name": "beta",
  "lb": 0.1,
  "ub": 0.2,
  "time": 22
  "label": "any"
}
```

**Comment by dmosaphir** [comment]
@danbryce  I have some questions on this, since the examples I was thinking of earlier (from the July 2023 evaluation) have time-dependent parameters, but the time-dependence in the AMR appears to be folded in at the transition-level rather than the parameter-level.  I was wondering if you knew of any instances where the AMR expressed the time dependence within the parameter?  

Example: This [Petri net AMR](https://github.com/siftech/funman/blob/main/resources/amr/petrinet/mira/models/scenario2_a_beta_scale_var_fixed.json) has a piecewise-defined beta.  However, the fact that it is time-dependent is folded in not at the beta parameter (which is set to the constant value  0.048081000000000006) but rather in the transitions that include beta, ex: starting at line 1027 of the linked AMR:

`    {
     "target": "t1",
     "expression": "I*S*ai*beta*Piecewise((1, (t >= 0) & (t < 82)), (0.4, (t >= 82) & (t < 198)), (0.55, (t >= 198) & (t < 282)), (0.6, (t >= 282) & (t < 327)), (0.55, (t >= 327) & (t < 370)), (0.3, (t >= 370) & (t < 429)), (0.4, (t >= 429) & (t < 468)), (0.15, (t >= 468) & (t < 527)), (0.2, (t >= 527) & (t < 548)), (0.3, (t >= 548) & (t < 562)), (0.35, (t >= 562) & (t < 609)), (0.4, (t >= 609) & (t < 670)), (0.5, (t >= 670) & (t < 731)), (0.4, (t >= 731) & (t < 1096)), (1, True))",
     "expression_mathml": "<apply><times/><ci>I</ci><ci>S</ci><ci>ai</ci><ci>beta</ci><piecewise><piece><cn>1</cn><apply><and/><apply><geq/><ci>t</ci><cn>0</cn></apply><apply><lt/><ci>t</ci><cn>82</cn></apply></apply></piece><piece><cn>0.40000000000000002</cn><apply><and/><apply><geq/><ci>t</ci><cn>82</cn></apply><apply><lt/><ci>t</ci><cn>198</cn></apply></apply></piece><piece><cn>0.55000000000000004</cn><apply><and/><apply><geq/><ci>t</ci><cn>198</cn></apply><apply><lt/><ci>t</ci><cn>282</cn></apply></apply></piece><piece><cn>0.59999999999999998</cn><apply><and/><apply><geq/><ci>t</ci><cn>282</cn></apply><apply><lt/><ci>t</ci><cn>327</cn></apply></apply></piece><piece><cn>0.55000000000000004</cn><apply><and/><apply><geq/><ci>t</ci><cn>327</cn></apply><apply><lt/><ci>t</ci><cn>370</cn></apply></apply></piece><piece><cn>0.29999999999999999</cn><apply><and/><apply><geq/><ci>t</ci><cn>370</cn></apply><apply><lt/><ci>t</ci><cn>429</cn></apply></apply></piece><piece><cn>0.40000000000000002</cn><apply><and/><apply><geq/><ci>t</ci><cn>429</cn></apply><apply><lt/><ci>t</ci><cn>468</cn></apply></apply></piece><piece><cn>0.14999999999999999</cn><apply><and/><apply><geq/><ci>t</ci><cn>468</cn></apply><apply><lt/><ci>t</ci><cn>527</cn></apply></apply></piece><piece><cn>0.20000000000000001</cn><apply><and/><apply><geq/><ci>t</ci><cn>527</cn></apply><apply><lt/><ci>t</ci><cn>548</cn></apply></apply></piece><piece><cn>0.29999999999999999</cn><apply><and/><apply><geq/><ci>t</ci><cn>548</cn></apply><apply><lt/><ci>t</ci><cn>562</cn></apply></apply></piece><piece><cn>0.34999999999999998</cn><apply><and/><apply><geq/><ci>t</ci><cn>562</cn></apply><apply><lt/><ci>t</ci><cn>609</cn></apply></apply></piece><piece><cn>0.40000000000000002</cn><apply><and/><apply><geq/><ci>t</ci><cn>609</cn></apply><apply><lt/><ci>t</ci><cn>670</cn></apply></apply></piece><piece><cn>0.5</cn><apply><and/><apply><geq/><ci>t</ci><cn>670</cn></apply><apply><lt/><ci>t</ci><cn>731</cn></apply></apply></piece><piece><cn>0.40000000000000002</cn><apply><and/><apply><geq/><ci>t</ci><cn>731</cn></apply><apply><lt/><ci>t</ci><cn>1096</cn></apply></apply></piece><otherwise><cn>1</cn></otherwise></piecewise></apply>"
    },`

**Comment by danbryce** [comment]
We have been handling parameters specified in the model as they appear natively, but allowing our request to override the model parameters.

If IIUC, the beta is still the parameter, but it’s multiplied by the `Piecewise` function.  I’d say that we already handle this (minus the support for the piecewise function). IMO the piecewise function is not related to the parameter, but rather the rate law.  

If we wanted to express a piecewise beta, we’d need something of the form:

Model rate law: I*S*ai*beta 

Request parameters:

{
	“name”: “beta”,
	“lb”: 0.04808 * 1,
	“ub” 0.04808 * 1,
	“time”: [0, 82)
},

{
	“name”: “beta”,
	“lb”: 0.04808 * 0.4,
	“ub” 0.04808 * 0.4,
	“time”: [82, 198)
},


I’m not sure how much we care about doing this in the request if people are already happy with this other method.

**Comment by danbryce** [comment]
Time is not being stored in the parameters, but rather comes into the custom rate laws
