### ISSUE TITLE
[FEAT] Support for observables

### ISSUE THREAD

**Issue by liunelson** [siftech/funman#48]
@danbryce @dmosaphir 

We want to solve problems like the 18-month epi evaluation scenario 2 question 6b
https://github.com/DARPA-ASKEM/program-milestones/tree/main/18-month-milestone/evaluation/Epi%20Use%20Case

Assuming a stratified model with variables `S_unvax_age1, S_unvax_age2, ..., S_vax_age1, S_vax_age2, ..., I_unvax_age1, ...`

We'd have observables `N_unvax = \sum X_unvax_i, S_unvax = \sum S_unvax_i, ...` over which model checks could be applied.

![Screenshot 2024-09-12 at 11 03 40 AM](https://github.com/user-attachments/assets/f5db8b52-fc30-478a-8507-19a22828bb85)

**Comment by liunelson** [comment]
Here's an example of a model with a non-trivial observable expression (`R0`):
[SIDARTHE model with observables.json](https://github.com/user-attachments/files/16981676/SIDARTHE.model.with.observables.json)

**Comment by danbryce** [comment]
@liunelson  Thanks for the pointers.  I want to make sure I understand the calculations needed (please correct me if I misunderstand).  They are:

- R0: expressed over the model parameters
- TotalInfected: expressed over the model state variables

The R0 observable is not a function of time, whereas TotalInfected is a function of time.  

In stratified models, these could be further expanded to aggregate the strata.  My understanding is that the AMR will be"flattened", meaning that any reindexing of the variables due to the strata will be present and there is not need to infer that the model is stratified.

**Comment by danbryce** [comment]
Ok, my plan is to define the values of the observables so that static ones like `R0` are untimed and time-dependent ones like `TotalInfected` are time indexed as `TotalInfected_0`, `TotalInfected_1`, `TotalInfected_2` ...

**Comment by danbryce** [comment]
The develop branch (b71d78c9f7c401e02fc3aa0c4777f42c2f836927) now has support for observables.  For an example, see [notebooks/monthly-demos/funman_sep_2024_observables.ipynb](https://github.com/siftech/funman/blob/develop/notebooks/monthly-demos/funman_sep_2024_observables.ipynb).

The example uses the [AMR file](https://github.com/siftech/funman/blob/develop/resources/amr/petrinet/monthly-demo/2024-09/SIDARTHE.model.with.observables.json) and [FUNMAN Request](https://github.com/siftech/funman/blob/develop/resources/amr/petrinet/monthly-demo/2024-09/eval_scenario_base_request.json).  The request constrains the observables with the following `constraint` block in the request:

```
[
      {
         "name": "TotalInfected_ub",
         "variable": "TotalInfected",
         "interval": {
            "ub": 0.1
         }
      },
      {
         "name": "R0_lb",
         "variable": "R0",
         "interval": {
            "lb": 0.1
         }
      }
   ]
```

The constraints respectively upper bound the `TotalInfected` and lower bound the `R0` observables.  The constraints are identical to those that constrain state variables, effectively treating observations as if they were additional state variables.
