### ISSUE TITLE
Allow unspecified parameter_bounds in API requests

### ISSUE THREAD

**Issue by jgladwig** [siftech/funman#6]
Currently at least one of the supported models (bilayer) requires that the parameter_bounds are full specified when making a query request to the API. This should be fixed to allow parameter_bounds to be unspecified or partially specified such that anything that the specified bounds take effect but all others take on reasonable defaults.

Reference: https://github.com/siftech/funman/blob/fe3203b316e75a279fde6140f019fb9dd3b96f5b/test/test_api.py#L86-L89

**Comment by danbryce** [comment]
Add tests that exercise unspecified bounds on all relevant models.
